// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright  Google LLC

// snippet.show
import GoogleCloudWkt
import GoogleCloudSecurityPubliccaV1
import Foundation

func sample(client: some PublicCertificateAuthorityService) async throws {
  let response = try await client.createExternalAccountKey(
    request: CreateExternalAccountKeyRequest( /* set fields */)
  )
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudSecurityPubliccaV1.Clients
        .PublicCertificateAuthorityServiceClient()
      try await sample(client: client)
    } catch {
      print("Error: \(error)")
    }
  }
}
