// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Creates a new
/// [ExternalAccountKey][google.cloud.security.publicca.v1.ExternalAccountKey] in
/// a given project.
public struct CreateExternalAccountKeyRequest: Codable, Equatable {
  /// Required. The parent resource where this external_account_key will be
  /// created. Format: projects/[project_id]/locations/[location]. At present
  /// only the "global" location is supported.
  public var parent: String

  /// Required. The external account key to create. This field only exists to
  /// future-proof the API. At present, all fields in ExternalAccountKey are
  /// output only and all values are ignored. For the purpose of the
  /// CreateExternalAccountKeyRequest, set it to a default/empty value.
  public var externalAccountKey: ExternalAccountKey?

  /// Initialize a new instance of `CreateExternalAccountKeyRequest`.
  public init(
    parent: String = String(),
    externalAccountKey: ExternalAccountKey? = nil,
  ) {
    self.parent = parent
    self.externalAccountKey = externalAccountKey
  }
}
