// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt

/// A representation of an ExternalAccountKey used for [external account
/// binding](https://tools.ietf.org/html/rfc8555#section-7.3.4) within ACME.
public struct ExternalAccountKey: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Resource name.
  /// projects/{project}/locations/{location}/externalAccountKeys/{key_id}
  public var name: String

  /// Output only. Key ID.
  /// It is generated by the PublicCertificateAuthorityService
  /// when the ExternalAccountKey is created
  public var keyId: String

  /// Output only. Base64-URL-encoded HS256 key.
  /// It is generated by the PublicCertificateAuthorityService
  /// when the ExternalAccountKey is created
  public var b64MacKey: Data

  /// Initialize a new instance of `ExternalAccountKey`.
  public init(
    name: String = String(),
    keyId: String = String(),
    b64MacKey: Data = Data(),
  ) {
    self.name = name
    self.keyId = keyId
    self.b64MacKey = b64MacKey
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.security.publicca.v1.ExternalAccountKey"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
