// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Manages the resources required for ACME [external account
/// binding](https://tools.ietf.org/html/rfc8555#section-7.3.4) for
/// the public certificate authority service.
public class PublicCertificateAuthorityService {
  /// Creates a new
  /// [ExternalAccountKey][google.cloud.security.publicca.v1.ExternalAccountKey]
  /// bound to the project.
  public func createExternalAccountKey(request: CreateExternalAccountKeyRequest) async throws
    -> ExternalAccountKey
  {
    fatalError("Unimplemented")
  }
}
