// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax

import GoogleCloudWkt

/// Manages the resources required for ACME [external account
/// binding](https://tools.ietf.org/html/rfc8555#section-7.3.4) for
/// the public certificate authority service.
///
/// @Snippet(path: "PublicCertificateAuthorityServiceQuickstart")
public protocol PublicCertificateAuthorityService {
  /// Creates a new
  /// [ExternalAccountKey][google.cloud.security.publicca.v1.ExternalAccountKey]
  /// bound to the project.
  ///
  /// [google.cloud.security.publicca.v1.ExternalAccountKey]: <doc:ExternalAccountKey>
  ///
  /// @Snippet(path: "PublicCertificateAuthorityService_CreateExternalAccountKey")
  func createExternalAccountKey(request: CreateExternalAccountKeyRequest) async throws
    -> ExternalAccountKey
}

extension Clients {
  /// The recommended implementation for ``PublicCertificateAuthorityService``.
  public class PublicCertificateAuthorityServiceClient: PublicCertificateAuthorityService {
    let inner: GoogleCloudGax.HTTPClient

    /// Creates a new `PublicCertificateAuthorityServiceClient` instance.
    public init(
      endpoint: String? = nil,
      credentials: GoogleCloudAuth.Credentials? = nil,
      session: URLSession? = nil,
    ) throws {
      let endpoint = endpoint ?? "https://publicca.googleapis.com"
      self.inner = try GoogleCloudGax.HTTPClient(
        endpoint: endpoint, credentials: credentials, session: session)
    }

    /// See `PublicCertificateAuthorityService.createExternalAccountKey`
    public func createExternalAccountKey(request: CreateExternalAccountKeyRequest) async throws
      -> ExternalAccountKey
    {
      let path = try { () throws -> String in
        guard let pathVariable0 = request.parent as String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/externalAccountKeys"
      }()
      let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      if let body = request.externalAccountKey {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, response) = try await self.inner.data(for: req)
      if !(200..<300).contains(response.statusCode) {
        throw GoogleCloudGax.RequestError.http(
          GoogleCloudGax.HTTPDetails(
            http_status_code: response.statusCode,
            headers: [:],
            payload: data,
          ))
      }
      return try GoogleCloudGax.ProtoJSONDecoder().decode(ExternalAccountKey.self, from: data)
    }
  }
}

// Default implementations
extension PublicCertificateAuthorityService {
  public func createExternalAccountKey(request: CreateExternalAccountKeyRequest) async throws
    -> ExternalAccountKey
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
